### ISSUE TITLE
Some perks are using the wrong id numbers.

### ISSUE THREAD

**Issue by AzumahBlue** [mlsof21/DIMWishlistBuilder#10]
I was working on Vouchsafe and Vorpal, the app uses id 3418165135 (enhanced vorpal) when it should be using id 1546637391 (regular vorpal.) That's just one example of many perks using the wrong id.

**Comment by mlsof21** [comment]
The way I'm getting the perk id is by matching the icon path url to a perk id. It appears that both the normal perk and the enhanced perk use the same icon path.

**Comment by mlsof21** [comment]
For now, I can bypass the enhanced perk matching by filtering it out, but I also don't see D2Gunsmith displaying those perks yet, despite DIM having them.

**Comment by AzumahBlue** [comment]
Ah, gunsmith, hasn't added the enhanced perks yet, we may have to wait for that.

**Comment by mlsof21** [comment]
It will still be an issue when they add it. There's no data in the html markup that indicates the perk id. The only I have to go off of is the perk icon path. If those are the same for both the normal perk and the enhanced version, then there's more that I'll have to do in order to correctly match perk ids. Maybe it'll be easier when Gunsmith gets updated, but we'll have to see.
